In [1]:
# written by gery
# Mar 20, 2018
# usage of seed
import tensorflow as tf

In [2]:
x=tf.random_normal([2,3], seed=2018)
with tf.Session() as sess:
    print sess.run(x)
    print sess.run(x)
    print sess.run(x)

[[ 1.9220369  -0.9028905  -0.37554395]
 [-1.3767949  -0.607995    1.0616063 ]]
[[-0.7868946  -0.7193138  -0.8043062 ]
 [ 0.40985426 -0.68113154  2.017941  ]]
[[-0.2757578  -1.5673585  -0.11042685]
 [ 0.73011726 -0.83859825 -0.454174  ]]


In [3]:
x=tf.random_normal([2,3], seed=53)
with tf.Session() as sess:
    print sess.run(x)
    print sess.run(x)
    print sess.run(x)

[[-0.33390483  0.41900244  0.2365525 ]
 [ 0.77084    -0.2895062  -0.5075657 ]]
[[ 1.0842199   0.41060048 -0.56223303]
 [ 0.21299118 -0.12898405  0.28654882]]
[[ 2.4757357  -0.28997052 -0.9092855 ]
 [ 0.21699283  0.39220488  1.2969818 ]]


In [4]:
x=tf.random_normal([2,3], seed=2018)
with tf.Session() as sess:
    print sess.run(x)
    print sess.run(x)
    print sess.run(x)

[[ 1.9220369  -0.9028905  -0.37554395]
 [-1.3767949  -0.607995    1.0616063 ]]
[[-0.7868946  -0.7193138  -0.8043062 ]
 [ 0.40985426 -0.68113154  2.017941  ]]
[[-0.2757578  -1.5673585  -0.11042685]
 [ 0.73011726 -0.83859825 -0.454174  ]]


In [5]:
x=tf.random_normal([2,3], seed=53)
with tf.Session() as sess:
    print sess.run(x)
    print sess.run(x)
    print sess.run(x)

[[-0.33390483  0.41900244  0.2365525 ]
 [ 0.77084    -0.2895062  -0.5075657 ]]
[[ 1.0842199   0.41060048 -0.56223303]
 [ 0.21299118 -0.12898405  0.28654882]]
[[ 2.4757357  -0.28997052 -0.9092855 ]
 [ 0.21699283  0.39220488  1.2969818 ]]
