The difference between `tf.nn.bias_add()` and `tf.add()`

In [1]:
import tensorflow as tf

In [2]:
sess = tf.Session()

In [3]:
a = tf.constant([[1.0, 2.0],[1.0, 2.0],[1.0, 2.0]])
b = tf.constant([1.0,2.0])
c = tf.constant([1.0])

In [4]:
print sess.run(a)
print sess.run(b)
print sess.run(c)

[[1. 2.]
 [1. 2.]
 [1. 2.]]
[1. 2.]
[1.]


# print sess.run(tf.nn.bias_add(a, c))  # error

In [5]:
print sess.run(tf.nn.bias_add(a, b))

[[2. 4.]
 [2. 4.]
 [2. 4.]]


In [6]:
print sess.run(tf.add(a, c))

[[2. 3.]
 [2. 3.]
 [2. 3.]]
