In [1]:
import tensorflow as tf

## for tensor

In [2]:
a = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype = "float32")
b = tf.constant([[[.1, .2, .3], [.4, .5, .6]], [[.7, .8, .9], [.10, .11, .12]]], dtype = "float32")

In [4]:
with tf.Session() as sess:
    print 'a = '
    print sess.run(a)
    print '---------------------------------------------------'
    print 'b = '
    print sess.run(b)
    print '---------------------------------------------------'
    print 'tf.concat([a, b], 0) = '
    print sess.run(tf.concat([a, b], 0))
    print '---------------------------------------------------'
    print 'tf.concat([a, b], 1) = '
    print sess.run(tf.concat([a, b], 1))
    print '---------------------------------------------------'
    print 'tf.concat([a, b], 2) = '
    print sess.run(tf.concat([a, b], 2))

a = 
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
---------------------------------------------------
b = 
[[[0.1  0.2  0.3 ]
  [0.4  0.5  0.6 ]]

 [[0.7  0.8  0.9 ]
  [0.1  0.11 0.12]]]
---------------------------------------------------
tf.concat([a, b], 0) = 
[[[ 1.    2.    3.  ]
  [ 4.    5.    6.  ]]

 [[ 7.    8.    9.  ]
  [10.   11.   12.  ]]

 [[ 0.1   0.2   0.3 ]
  [ 0.4   0.5   0.6 ]]

 [[ 0.7   0.8   0.9 ]
  [ 0.1   0.11  0.12]]]
---------------------------------------------------
tf.concat([a, b], 1) = 
[[[ 1.    2.    3.  ]
  [ 4.    5.    6.  ]
  [ 0.1   0.2   0.3 ]
  [ 0.4   0.5   0.6 ]]

 [[ 7.    8.    9.  ]
  [10.   11.   12.  ]
  [ 0.7   0.8   0.9 ]
  [ 0.1   0.11  0.12]]]
---------------------------------------------------
tf.concat([a, b], 2) = 
[[[ 1.    2.    3.    0.1   0.2   0.3 ]
  [ 4.    5.    6.    0.4   0.5   0.6 ]]

 [[ 7.    8.    9.    0.7   0.8   0.9 ]
  [10.   11.   12.    0.1   0.11  0.12]]]


## for  matrix

In [5]:
a = tf.constant([[1, 2, 3], [4, 5, 6]], dtype = "float32")
b = tf.constant([[.1, .2, .3], [.4, .5, .6]], dtype = "float32")

In [6]:
with tf.Session() as sess:
    print 'a = '
    print sess.run(a)
    print '---------------------------------------------------'
    print 'b = '
    print sess.run(b)
    print '---------------------------------------------------'
    print 'tf.concat([a, b], 0) = '
    print sess.run(tf.concat([a, b], 0))
    print '---------------------------------------------------'
    print 'tf.concat([a, b], 1) = '
    print sess.run(tf.concat([a, b], 1))

a = 
[[1. 2. 3.]
 [4. 5. 6.]]
---------------------------------------------------
b = 
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
---------------------------------------------------
tf.concat([a, b], 0) = 
[[1.  2.  3. ]
 [4.  5.  6. ]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]]
---------------------------------------------------
tf.concat([a, b], 1) = 
[[1.  2.  3.  0.1 0.2 0.3]
 [4.  5.  6.  0.4 0.5 0.6]]
