`tf.nn.dropout(x, keep_prob, noise_shape=None, seed=None, name=None)`.

Each element has probability `keep_prob` to change to $\frac{x_k}{keep\_prob}$, otherwise change to $0$, if $x=[x_1,\cdots ,x_n]$.

In [1]:
import tensorflow as tf

In [2]:
a=tf.ones([3,2,4])
print a

Tensor("ones:0", shape=(3, 2, 4), dtype=float32)


In [3]:
sess=tf.Session()
# sess.run()

In [4]:
print sess.run(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [5]:
b = tf.nn.dropout(a, .1)
print sess.run(b)

[[[ 0.  0.  0.  0.]
  [10.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [6]:
b = tf.nn.dropout(a, .5)
print sess.run(b)

[[[2. 0. 0. 2.]
  [2. 2. 2. 0.]]

 [[2. 2. 2. 2.]
  [0. 0. 2. 0.]]

 [[0. 0. 2. 0.]
  [2. 2. 0. 0.]]]
