In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = np.random.sample((12, 2))
y = np.random.sample((12, 1))
dataset = tf.data.Dataset.from_tensor_slices((x, y))
# dataset = dataset.apply(tf.contrib.data.batch_and_drop_remainder(2))
dataset = dataset.batch(3)

In [3]:
print x
print y

[[0.66208996 0.04292221]
 [0.40337062 0.23407214]
 [0.43132371 0.20497535]
 [0.818834   0.306416  ]
 [0.72430116 0.86123285]
 [0.65117373 0.02559928]
 [0.00450653 0.33346128]
 [0.89535385 0.91746591]
 [0.47134211 0.95232249]
 [0.32237978 0.82316076]
 [0.12249933 0.58686224]
 [0.87559846 0.98549353]]
[[0.13003201]
 [0.22791615]
 [0.03040132]
 [0.55030984]
 [0.1645152 ]
 [0.40598396]
 [0.91266362]
 [0.59463914]
 [0.26064259]
 [0.20728853]
 [0.98810327]
 [0.1691056 ]]


In [4]:
# dataset = dataset.repeat(2)
iterator = dataset.make_initializable_iterator()
el = iterator.get_next()
with tf.Session() as sess:
    sess.run(iterator.initializer)
    for i in range(4):
        print(sess.run(el))

(array([[0.66208996, 0.04292221],
       [0.40337062, 0.23407214],
       [0.43132371, 0.20497535]]), array([[0.13003201],
       [0.22791615],
       [0.03040132]]))
(array([[0.818834  , 0.306416  ],
       [0.72430116, 0.86123285],
       [0.65117373, 0.02559928]]), array([[0.55030984],
       [0.1645152 ],
       [0.40598396]]))
(array([[0.00450653, 0.33346128],
       [0.89535385, 0.91746591],
       [0.47134211, 0.95232249]]), array([[0.91266362],
       [0.59463914],
       [0.26064259]]))
(array([[0.32237978, 0.82316076],
       [0.12249933, 0.58686224],
       [0.87559846, 0.98549353]]), array([[0.20728853],
       [0.98810327],
       [0.1691056 ]]))
