In [1]:
'''
This notebook contains examples on operations of
  tf.constant(), tf.matmul(), tf.add()
'''
# written by gery
# Mar 20, 2018
import tensorflow as tf
import numpy as np

In [2]:
# create a 3-D tensor
# a = tf.constant(np.arange(1, 2), shape=[2,1,3], dtype=np.float32)
a = tf.constant([[[1.0, 1.0, 1.0]],[[0, 0, 1.0]]], dtype=np.float32)

In [3]:
'''
creat a 3-D tensor with 2 matrices with each has size of 3-by-4
'''
b = tf.constant(np.arange(1,25), shape=[2, 3, 4],  dtype=np.float32)

In [4]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print sess.run(a)
    print sess.run(b)

[[[1. 1. 1.]]

 [[0. 0. 1.]]]
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]


In [5]:
with tf.Session() as sess:
    print sess.run(tf.matmul(a,b))

[[[15. 18. 21. 24.]]

 [[21. 22. 23. 24.]]]


In [6]:
c = tf.constant([[[1.0, 1.0, 1.0]],[[2, 2, 2]]], dtype=np.float32)
with tf.Session() as sess:
    print sess.run(a)
    print sess.run(c)

[[[1. 1. 1.]]

 [[0. 0. 1.]]]
[[[1. 1. 1.]]

 [[2. 2. 2.]]]


In [7]:
with tf.Session() as sess:
    print sess.run(tf.add(a,c))

[[[2. 2. 2.]]

 [[2. 2. 3.]]]
