In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
tf.InteractiveSession()

In [3]:
tf.stack([a, b], axis=0).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [4]:
tf.stack([a, b], axis=1).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [5]:
c = tf.Variable([a, b])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print sess.run(c)

[[1 2 3]
 [4 5 6]]


In [6]:
c = tf.Variable([a, b])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print 'c=',sess.run(c)
    d = tf.reshape(c, [-1])
    print type(d)
    print sess.run(d)

c= [[1 2 3]
 [4 5 6]]
<class 'tensorflow.python.framework.ops.Tensor'>
[1 2 3 4 5 6]
