# Merge two tensor into one

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

## tf.stack()

In [3]:
tf.InteractiveSession()
tf.stack([a, b], axis=0).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [4]:
tf.stack([a, b], axis=1).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

## tf.Variable()

In [5]:
c = tf.Variable([a, b])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print sess.run(c)

[[1 2 3]
 [4 5 6]]


## tf.reshape()

In [6]:
a = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print 'a = '
    print sess.run(a)
    print '---------------------------------------------------'
    print 'tf.reshape(a, [12]) ='
    print sess.run(tf.reshape(a, [12]))
    print '---------------------------------------------------'
    print 'tf.reshape(a, [3, 4]) ='
    print sess.run(tf.reshape(a, [3, 4]))
    print '---------------------------------------------------'
    print 'tf.reshape(a, [12, 1]) ='
    print sess.run(tf.reshape(a, [12, 1]))
    print '---------------------------------------------------'
    print 'tf.reshape(a, [2, 1, 6]) ='
    print sess.run(tf.reshape(a, [2, 1, 6]))

a = 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
---------------------------------------------------
tf.reshape(a, [12]) =
[ 1  2  3  4  5  6  7  8  9 10 11 12]
---------------------------------------------------
tf.reshape(a, [3, 4]) =
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------------------------------------------------
tf.reshape(a, [12, 1]) =
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
---------------------------------------------------
tf.reshape(a, [2, 1, 6]) =
[[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]]
